services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres-cgd-compose"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - db_cgd_volume:/data/postgres-db-cgd
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  db_cgd_volume:
    external: true